sp500_analytics:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('SUPABASE_DB_HOST') }}"
      user: "{{ env_var('SUPABASE_DB_USER') }}"
      password: "{{ env_var('SUPABASE_DB_PASSWORD') }}"
      port: 5432
      dbname: postgres
      schema: public
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10
      retries: 3
