name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Configure Pylint
      run: |
        echo "[FORMAT]" >> .pylintrc
        echo "max-line-length = 120" >> .pylintrc
        echo "" >> .pylintrc
        echo "[MESSAGES CONTROL]" >> .pylintrc
        echo "disable = missing-module-docstring" >> .pylintrc
        echo "" >> .pylintrc
        echo "[TYPECHECK]" >> .pylintrc
        echo "disable = import-error" >> .pylintrc
        echo "" >> .pylintrc
        echo "[DESIGN]" >> .pylintrc
        echo "argument-naming-style = snake_case" >> .pylintrc
        echo "" >> .pylintrc
        echo "[NAMING]" >> .pylintrc
        echo "variable-rgx = [a-z_][a-z0-9_]{2,30}$" >> .pylintrc
        echo "" >> .pylintrc
        echo "[BASIC]" >> .pylintrc
        echo "good-exceptions = Exception" >> .pylintrc
        echo "" >> .pylintrc
        echo "[LOGGING]" >> .pylintrc
        echo "logging-format-style = percent" >> .pylintrc
    - name: Analysing the code with pylint
      run: |
        pylint --rcfile=.pylintrc $(git ls-files '*.py')
